# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestdemo():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_testdemo(self):
    # Test name: test-demo
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.baidu.com/")
    # 2 | setWindowSize | 968x1020 | 
    self.driver.set_window_size(968, 1020)
    # 3 | click | css=area | 
    self.vars["window_handles"] = self.driver.window_handles
    # 4 | storeWindowHandle | root | 
    self.driver.find_element(By.CSS_SELECTOR, "area").click()
    # 5 | selectWindow | handle=${win1214} | 
    self.vars["win1214"] = self.wait_for_window(2000)
    # 6 | close |  | 
    self.vars["root"] = self.driver.current_window_handle
    # 7 | selectWindow | handle=${root} | 
    self.driver.switch_to.window(self.vars["win1214"])
    # 8 | click | name=wd | 
    self.driver.close()
    # 9 | type | id=kw | zhihu
    self.driver.switch_to.window(self.vars["root"])
    # 10 | click | css=.bdsug-s | 
    self.driver.find_element(By.NAME, "wd").click()
    # 11 | runScript | window.scrollTo(0,679) | 
    self.driver.find_element(By.ID, "kw").send_keys("zhihu")
    # 12 | runScript | window.scrollTo(0,596) | 
    self.driver.find_element(By.CSS_SELECTOR, ".bdsug-s").click()
    # 13 | close |  | 
    self.driver.execute_script("window.scrollTo(0,679)")
    self.driver.execute_script("window.scrollTo(0,596)")
    self.driver.close()
  
